config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :owners
  resources :animals
  resources :pets
  resources :visits
  resources :dosages
  resources :treatments
  resources :medicines
  resources :procedures

  # Routes for mecidine and procedure costs
  get 'medicine_costs/new', to: 'medicine_costs#new', as: :new_medicine_cost
  get 'procedure_costs/new', to: 'procedure_costs#new', as: :new_procedure_cost
  post 'medicine_costs', to: 'medicine_costs#create', as: :medicine_costs
  post 'procedure_costs', to: 'procedure_costs#create', as: :procedure_costs

  # Other custom routes
  get 'visits/:id/dosages', to: 'visits#dosages', as: :visit_dosages

  # Routes for searching
  # get 'medicines/search', to: 'medicines#search', as: :medicine_search
  # get 'owners/search', to: 'owners#search', as: :owner_search
  # get 'pets/search', to: 'pets#search', as: :pet_search

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/visit.rb
class Visit < ApplicationRecord
  # Relationships
  # -----------------------------
  belongs_to :pet
  has_one :animal, through: :pet
  has_many :dosages
  has_many :treatments
  has_one :owner, through: :pet
  # has_many :notes, as: :notable
  
  
  # Scopes
  # -----------------------------
  # by default, order by visits in descending order (most recent first)
   scope :chronological, lambda { order('date DESC') }
   # get all the visits by a particular pet (using the 'stabby lambda' notation here)
   scope :for_pet, ->(pet_id) { where('pet_id = ?', pet_id) }
   # get the last X visits (using the 'stabby lambda' notation here)
   scope :last_x, ->(num) { limit(num).order('date DESC') }

  
  # Validations
  # -----------------------------
  # old style validation for presence_of pet_id b/c only validation for that attribute
  validates_presence_of :pet_id

  # date must be a valid date
  validates_date :date

  # weight must be present and a number greater than 0 and less than 100 (none of our animal types will exceed)
  validates :weight, presence: true, numericality: { greater_than: 0, less_than: 100 }

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # A callback to set up an @visit object to work with 
  before_action :set_visit, only: [:show, :edit, :update, :destroy, :dosages]
  before_action :check_login
  authorize_resource

  def index
    # get all visits in reverse chronological order, 10 per page
    if current_user.owner?
      @visits = current_user.owner.visits.chronological.paginate(page: params[:page]).per_page(10)
    else
      @visits = Visit.chronological.paginate(page: params[:page]).per_page(10)
    end
  end
  
  def show
    get_related_data()
  end
  
  def new
    @visit = Visit.new
  end
  
  def create
    @visit = Visit.new(visit_params)
    if @visit.save
      flash[:notice] = "Successfully added visit for #{@visit.pet.name}."
      redirect_to @visit
    else
      render action: 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @visit.update(visit_params)
      flash[:notice] = "Successfully updated visit by #{@visit.pet.name}."
      redirect_to @visit
    else
      render action: 'edit'
    end
  end
  
  def destroy
    ## We are no longer allowing visits to be destroyed
    # if @visit.destroy
    #   flash[:notice] = "Successfully removed the visit of #{@visit.pet.name} on #{@visit.date.strftime('%b %e')}."
    #   redirect_to visits_url
    # else
    #   get_related_data()
    #   render action: 'show'
    # end
    flash[:notice] = "Visits cannot be destroyed in the PATS system"
    redirect_to @visit
  end

  def dosages
    @dosages = Dosage.for_visit(@visit.id).joins(:medicine).select('dosages.*, medicines.name as medicine_name')
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:pet_id, :date, :weight)
    end
    def get_related_data
      @pet = @visit.pet
      @owner = @visit.pet.owner
      # get all the dosages & treatments associated with this visit, if any
      # note the difference in the sorting (treatments > dosages in terms of clarity)
      @dosages = @visit.dosages.to_a.sort_by{|d| d.medicine.name}
      @treatments = @visit.treatments.alphabetical
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
  # create a helper to get the options for the pet select menu
  # will return an array with key being pet_name : owner_name so 
  # that vet can choose the right pet (many pets share same names)
  def get_pet_options
    Pet.active.alphabetical.map{|p| ["#{p.name} (#{p.animal.name}) : #{p.owner.name}", p.id] }
  end
end

app/views/visits/_fields.html.erb
<%= f.input :pet_id, collection: get_pet_options, include_blank: true %>
<%= f.input :weight, label_html: { class: 'active' } %>
<%= f.input :date, label_html: { class: 'active' } %>

app/views/visits/_form.html.erb
<%= simple_form_for(@visit) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :pet_id, collection: get_pet_options, include_blank: true %>
      <%= f.input :weight, label_html: { class: 'active' } %>
      <%= f.input :date, label_html: { class: 'active' } %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/visits/_visit_data.html.erb
<div class="card">
  <div class="card-content">
    <h5>Visit Data</h5><br />

    <b>Date:&nbsp;&nbsp;</b>
      <%= @visit.date.strftime("%B %d, %Y") %><br /><br />

    <b>Pet:&nbsp;&nbsp;</b>
      <%= link_to @pet.name, pet_path(@pet) %><br /><br />

    <b>Animal:&nbsp;&nbsp;</b>
      <%= @pet.animal.name %><br /><br />

    <b>Owner:&nbsp;&nbsp;</b>
      <%= link_to @owner.name, owner_path(@owner) %><br /><br />

    <b>Weight:&nbsp;&nbsp;</b>
      <%= @visit.weight %> lbs.<br /><br />

    <b>Total Charge:&nbsp;&nbsp;</b>
      <% @visit.total_charge ||= 0.00 %>
      <%= number_to_currency(@visit.total_charge/100.0) %><br /><br />
      
  </div>
</div>

app/views/visits/_visit_dosage_form_template.html.erb
<div id="form-template">
  <h5>New Dosage</h5>
  <!-- create an empty dosage object to work with -->
  <% @dosage = Dosage.new %>
  <!-- now the form template itself -->
  <div class="row">
    <div class="col">
      <%= simple_form_for(@dosage) do |f| %>
        <%= f.error_notification %>
        <div class="row">
          <div class="form-inputs">
            <%= f.input :medicine_id, collection: Medicine.for_animal(@pet.animal.id).active.alphabetical.to_a, include_blank: true %>
            <%= f.input :units_given, label_html: { class: 'active' } %>
            <%= f.input :discount, label_html: { class: 'active' } %>
            <%= f.input :visit_id, as: :hidden, input_html: { value: @visit.id } %>
          </div>
        </div>
        <div class="row">
          <div class="form-actions col">
            <%= f.button :submit %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/visits/_visit_dosages.html.erb
<% unless @dosages.empty? %>
  <div class="card yellow lighten-4">
    <div class="card-content">
      <span class="card-title">Dosages given</span>
      <ul>
        <% for dosage in @dosages %>
          <li>
            <% if can? :destroy, Dosage %>
              <%= link_to(dosage_path(dosage), method: :delete, class: 'remove') do %>
                x&nbsp;&nbsp;
              <% end %>
            <% end %>
            <%= link_to dosage.medicine.name, medicine_path(dosage.medicine) %>:&nbsp;&nbsp;
            <%= dosage.units_given %> <%= dosage.medicine.unit %>
          </li>
        <% end %>
      </ul>
    </div>
    <% if can? :new, Dosage %>
      <div class="card-action">
        <%= link_to "Add a new dosage", new_dosage_path(visit_id: @visit.id) %>
      </div>
    <% end %>
  </div>
<% else %>
  <% if can? :new, Dosage %>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add a new dosage", new_dosage_path(visit_id: @visit.id) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/visits/_visit_dosages_vue.html.erb
<div id="dosage_handling">
  <%= hidden_field_tag "visit_id", @visit.id %>
  <% unless @dosages.empty? %>
    <div class="card yellow lighten-4">
      <div class="card-content">
        <span class="card-title">Dosages given</span>
        <ul is='dosage-row' 
            v-for="dosage in dosages" 
            v-bind:dosage="dosage"
            class="no_bullet">  
        </ul>
      </div>
      <% if can? :new, Dosage %>
        <div class="card-action">
          <!-- Could bind title based on state, but chance to show v-else directive -->
          <div v-if="modal_open">
            <%= link_to "Cancel dosage", "#", {%s(v-on:click) => "switch_modal()"} %>
          </div>
          <div v-else>
            <%= link_to "Add a new dosage", "#", {%s(v-on:click) => "switch_modal()"} %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <% if can? :new, Dosage %>
      <div class="card grey lighten-3">
        <div class="card-action">
          <!-- Note in class that message not consistent with activity -->
          <%= link_to "Add a new dosage", "#", {%s(v-on:click) => "switch_modal()"} %>
        </div>
      </div>
    <% end %>
  <% end %>  

  <div v-if="modal_open">
    <new-dosage-form></new-dosage-form>
  </div>

</div> <!-- End of div#dosage_handling -->


<!-- Defining Vue templates to work with components -->
<script type="text/x-template" id="dosage-row">
  // Commenting this out b/c template in js file, but if I wanted it here...
  // <li>
  //   <a v-on:click="remove_record(dosage)" class="remove">x&nbsp;&nbsp;</a>
  //   {{ dosage.medicine_name }}:&nbsp;&nbsp;
  //   {{ dosage.units_given }}&nbsp;units
  // </li>
</script>

<!--  much easier to include this complicated template here 
      rather than in the js file (IMO) -->
<script type="text/x-template" id="dosage-form-template">
  <%= render "visit_dosage_form_template", locals: {pet: @pet, visit: @visit, dosage: Dosage.new} %>
</script>

app/views/visits/_visit_sidebar.html.erb
<%= render :partial => "visit_dosages_vue" %>
<br />
<%= render :partial => "visit_treatments" %>

app/views/visits/_visit_treatments.html.erb
<% unless @treatments.empty? %>
  <div class="card yellow lighten-4">
    <div class="card-content">
      <span class="card-title">Treatments given</span>
      <ul>
        <% for treatment in @treatments %>
          <li>
            <% if can? :destroy, Treatment %>
              <%= link_to(treatment_path(treatment), class: 'remove', method: :delete) do %>
                x&nbsp;&nbsp;
              <% end %>
            <% end %>
            <%= link_to treatment.procedure.name, procedure_path(treatment.procedure) %>
          </li>
        <% end %>
      </ul>
    </div>
    <% if can? :new, Treatment %>
      <div class="card-action">
        <%= link_to "Add a new treatment", new_treatment_path(visit_id: @visit.id) %>
      </div>
    <% end %>
  </div>
<% else %>
  <% if can? :new, Treatment %>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add a new treatment", new_treatment_path(visit_id: @visit.id) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/visits/_visits_list.html.erb
<!-- <h4>Visits at PATS</h4> -->
  <%= render :partial => "partials/title_with_search", locals: {title: "Visits at PATS"} %>

<table class="striped highlight">
  <thead>
    <th>Date</th>
    <th>Pet</th>
    <th>Weight</th>
    <th class="align_center">Options</th>
  </thead>
  <% for visit in @visits %>
    <tr>
      <td><%= link_to visit.date.strftime("%m/%d/%y"), visit_path(visit) %></td>
      <td><%= link_to visit.pet.name, pet_path(visit.pet) %> (<%= visit.pet.animal.name %>)</td>
      <td><%= visit.weight %> lbs</td>
      <td class="align_center">
      <% if can? :edit, visit %>
        <%= link_to edit_visit_path(visit) do %>
              <i class="material-icons">edit</i>
          <% end %>
          &nbsp;&nbsp;&nbsp;&nbsp; 
        <% end %>
        <% if can? :destroy, visit %>
          <%= link_to(visit_path(visit), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
              <i class="material-icons">delete</i>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<br />
<%= will_paginate @visits, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<p>&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'visit'} %>

app/views/visits/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @visit, 
                                                        type_of_form: "Edit Visit",
                                                        fields: "fields"} %>

app/views/visits/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "visit", 
                                                         primary: "visits_list", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/visits/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @visit, 
                                                        type_of_form: "New Visit",
                                                        fields: "fields"} %>

app/views/visits/show.html.erb
<%= render partial: "partials/structure2", locals: {model_name: "visit", 
                                                         object: @visit,
                                                         primary: "visit_data", 
                                                         secondary: nil,
                                                         sidebar: "visit_sidebar"} %>