config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :owners
  resources :animals
  resources :pets
  resources :visits
  resources :dosages
  resources :treatments
  resources :medicines
  resources :procedures

  # Routes for mecidine and procedure costs
  get 'medicine_costs/new', to: 'medicine_costs#new', as: :new_medicine_cost
  get 'procedure_costs/new', to: 'procedure_costs#new', as: :new_procedure_cost
  post 'medicine_costs', to: 'medicine_costs#create', as: :medicine_costs
  post 'procedure_costs', to: 'procedure_costs#create', as: :procedure_costs

  # Other custom routes
  get 'visits/:id/dosages', to: 'visits#dosages', as: :visit_dosages

  # Routes for searching
  # get 'medicines/search', to: 'medicines#search', as: :medicine_search
  # get 'owners/search', to: 'owners#search', as: :owner_search
  # get 'pets/search', to: 'pets#search', as: :pet_search

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/pet.rb
require 'helpers/activeable'
require 'helpers/validations'

class Pet < ApplicationRecord
  include Validations
  include Activeable::InstanceMethods
  extend Activeable::ClassMethods

  # Relationships
  # -----------------------------
  belongs_to :animal
  belongs_to :owner
  has_many :visits
  has_many :dosages, through: :visits
  has_many :treatments, through: :visits
  # has_many :notes, as: :notable


  # Scopes
  # -----------------------------
  # order pets by their name
  scope :alphabetical, -> { order('name') }
  # get all the pets we treat (not moved away or dead)
  # the code below now replaced with AppHelpers::Activeable::ClassMethods
  ## scope :active, -> { where(active: true) }
  ## ... which is really the same as (but shorter):
  ## def self.active
  ##   where(active: true)
  ## end
  ## get all the pets we heave treated that moved away or died
  ## scope :inactive, -> { where.not(active: true) }
  # get all the female pets
  scope :females, -> { where(female: true) }
  # get all the male pets
  scope :males, -> { where(female: false) }

  # get all the pets for a particular owner
  scope :for_owner, ->(owner_id) { where("owner_id = ?", owner_id) }
  # get all the pets who are a particular animal type
  scope :by_animal, ->(animal_id) { where("animal_id = ?", animal_id) }
  # get all the pets born before a certain date
  scope :born_before, ->(dob) { where('date_of_birth < ?', dob) }
  # find all pets that have a name like some term or are and animal like some term
  scope :search, ->(term) { joins(:animal).where('pets.name LIKE ?', "#{term}%").order("pets.name") }


  # Validations
  # -----------------------------
  # System note:   not requiring DOB because may not be known (e.g., adopted pet)
  # Teaching note: could have done validates_presence_of :name, but using a different
  #                method discussed in class to show alternative
  #
  # First, make sure a name exists
  validates :name, presence: true
  # Second, make sure the animal is one of the types PATS treats
  validate :animal_type_treated_by_PATS
  # Third, make sure the owner_id is in the PATS system 
  validate :owner_is_active_in_PATS_system
  

  # Misc Methods and Constants
  # -----------------------------
  # a method to get owner name in last, first format
  def gender
    self.female ? "Female" : "Male"
  end  

  # Use private methods to execute the custom validations
  # -----------------------------
  private
  def animal_type_treated_by_PATS
    is_active_in_system(:animal)
  end
  
  def owner_is_active_in_PATS_system
    is_active_in_system(:owner)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  # A callback to set up an @pet object to work with 
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    # get data on all pets and paginate the output to 10 per page
    if current_user.owner?
      @active_pets = current_user.owner.pets.active.alphabetical.paginate(page: params[:page]).per_page(10)
      @inactive_pets = current_user.owner.pets.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
    else
      @active_pets = Pet.active.alphabetical.paginate(page: params[:page]).per_page(10)
      @inactive_pets = Pet.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
    end

  end

  def show
    # get the last 10 visits for this pet
    @recent_visits = @pet.visits.chronological.last(10).to_a
  end

  def new
    @pet = Pet.new
  end

  def edit
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to @pet, notice: "Successfully added #{@pet.name} as a PATS pet."
    else
      render action: 'new'
    end
  end

  def update
    if @pet.update(pet_params)
      redirect_to @pet, notice: "Updated #{@pet.name}'s information"
    else
      render action: 'edit'
    end
  end

  def destroy
    @pet.make_inactive
    redirect_to pets_path, notice: "Deactivated #{@pet.name}"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pet
    @pet = Pet.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def pet_params
    params.require(:pet).permit(:name, :animal_id, :owner_id, :female, :date_of_birth, :active)
  end

end

app/views/pets/_active_pets.html.erb
<h4>Active Pets at PATS</h4>

<table class="striped highlight">
  <thead>
    <th>Pet</th>
    <th>Type</th>
    <th>Owner</th>
    <th class="align_center">Options</th>
  </thead>
  <% for pet in @active_pets %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to pet.name, pet_path(pet) %></td>
      <td><%= pet.animal.name %></td>
      <td><%= link_to pet.owner.name, owner_path(pet.owner) %></td>

    <td class="align_center">
      <% if can? :edit, pet %>
        <%= link_to edit_pet_path(pet) do %>
              <i class="material-icons">edit</i>
          <% end %>
          &nbsp;&nbsp;&nbsp;&nbsp; 
        <% end %>
        <% if can? :destroy, pet %>
          <%= link_to(pet_path(pet), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
              <i class="material-icons">delete</i>
          <% end %>
        <% end %>
    </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>
<br />
<%= will_paginate @active_pets, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<p>&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'pet'} %>

app/views/pets/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :animal_id, collection: Animal.alphabetical.active.to_a, include_blank: true %>
<%= f.input :owner_id, collection: Owner.alphabetical.active.to_a, include_blank: true %>
<%= f.input :date_of_birth, label_html: { class: 'active' } %>
<%= f.input :female, as: :radio_buttons %>
<%= f.input :active %>

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :name, label_html: { class: 'active' } %>
      <%= f.input :animal_id, collection: Animal.alphabetical.active.to_a, include_blank: true %>
      <%= f.input :owner_id, collection: Owner.alphabetical.active.to_a, include_blank: true %>
      <%= f.input :date_of_birth, label_html: { class: 'active' } %>
      <%= f.input :female, as: :radio_buttons %>
      <%= f.input :active %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/pets/_inactive_pets.html.erb
<br />
<% unless @inactive_pets.empty? %>
  <div class="card yellow lighten-4">
    <div class="card-content">
      <span class="card-title">Inactive Pets</span>
      <ul>
        <% for pet in @inactive_pets %>
          <li><%= link_to pet.name, pet_path(pet) %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/pets/_pet_data.html.erb
<div class="card">
  <div class="card-content">
    <h5>Pet Information for <%= @pet.name %></h5><br />

    <b>Owner:&nbsp;&nbsp;</b>
      <%= link_to @pet.owner.name, owner_path(@pet.owner) %><br /><br />

    <b>Type:&nbsp;&nbsp;</b>
      <%= @pet.animal.name %><br /><br />

    <b>Gender:&nbsp;&nbsp;</b>
      <%= @pet.gender %><br /><br />

    <b>Date of Birth:&nbsp;&nbsp;</b>
      <%= @pet.date_of_birth.strftime("%B %d, %Y") %><br /><br />

    <b>Active with PATS?&nbsp;&nbsp;</b>
      <%= @pet.active ? "Yes" : "No" %><br><br><br>
  </div>
</div>

app/views/pets/_pets_list.html.erb
<h4><%= state.capitalize %> Pets at PATS</h4>

  <table class="striped highlight">
    <thead>
      <th>Pet</th>
      <th>Type</th>
      <th>Owner</th>
      <th class="align_center">Options</th>
    </thead>
    <% for pet in object %>
      <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
        <td><%= link_to pet.name, pet_path(pet) %></td>
        <td><%= pet.animal_name %></td>
        <td><%= link_to pet.owner_name, owner_path(pet.owner_id) %></td>

      <td class="align_center">
        <% if can? :edit, pet %>
          <%= link_to edit_pet_path(pet) do %>
                <i class="material-icons">edit</i>
            <% end %>
            &nbsp;&nbsp;&nbsp;&nbsp; 
          <% end %>
          <% if can? :destroy, pet %>
            <%= link_to(pet_path(pet), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
                <i class="material-icons">delete</i>
            <% end %>
          <% end %>
      </td>
      </tr>
    <% end %>
  </table>
  <p class="supertiny"></p>
  <br />
  <%= will_paginate object, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>

app/views/pets/_recent_visits.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title">Recent Visits</span>
    <table class="striped highlight">
      <thead>
        <th>Visit</th>
        <th>Weight</th>
      </thead>
        <% for visit in @recent_visits %>
          <tr>
            <td><%= link_to visit.date.strftime("%m/%d/%y"), visit_path(visit) %></td>
          <td>&nbsp;<%= visit.weight %> lbs</td>
          </tr>
        <% end %>
    </table>
  </div>
</div>

app/views/pets/_tabbed_content.html.erb
<%= render partial: "partials/tabbed_content/all_tabs", locals: {tab_base: "pets", 
                                                         primary_object: @active_pets,
                                                         secondary_object: @inactive_pets,
                                                         tertiary_object: nil,
                                                         display_partial: ["pets_list","pets_list"],                                                         
                                                         states: ['active','inactive']} %>

<%= render :partial => "partials/add_new_object", locals: {model_name: 'pet'} %>

app/views/pets/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @pet, 
                                                        type_of_form: "Edit Pet",
                                                        fields: "fields"} %>

app/views/pets/index.html.erb
<%# render partial: "partials/structure1", locals: {model_name: "pet", 
                                                         primary: "active_pets", 
                                                         secondary: nil,
                                                         sidebar: "inactive_pets"} %>

<%= render partial: "partials/structure1", locals: {model_name: "pet", 
                                                         primary: "tabbed_content", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/pets/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @pet, 
                                                        type_of_form: "New Pet",
                                                        fields: "fields"} %>

app/views/pets/show.html.erb
<%= render partial: "partials/structure2", locals: {model_name: "pet", 
                                                         object: @pet,
                                                         primary: "pet_data", 
                                                         secondary: nil,
                                                         sidebar: "recent_visits"} %>