config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :owners
  resources :animals
  resources :pets
  resources :visits
  resources :dosages
  resources :treatments
  resources :medicines
  resources :procedures

  # Routes for mecidine and procedure costs
  get 'medicine_costs/new', to: 'medicine_costs#new', as: :new_medicine_cost
  get 'procedure_costs/new', to: 'procedure_costs#new', as: :new_procedure_cost
  post 'medicine_costs', to: 'medicine_costs#create', as: :medicine_costs
  post 'procedure_costs', to: 'procedure_costs#create', as: :procedure_costs

  # Other custom routes
  get 'visits/:id/dosages', to: 'visits#dosages', as: :visit_dosages

  # Routes for searching
  # get 'medicines/search', to: 'medicines#search', as: :medicine_search
  # get 'owners/search', to: 'owners#search', as: :owner_search
  # get 'pets/search', to: 'pets#search', as: :pet_search

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
<% if can? :new, eval(model_name.capitalize) %>
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>
<% end %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About PATS', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("profh@cmu.edu", "Klingon Code Warrior", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2018
  </div>

</div>

app/views/partials/_form2_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields1}", locals: { f: f } %>
            </div>
          </div>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div class="card grey lighten-3">
          <div class="row">
            <div class="card-content">
              <span class="card-title"><%= section_2 %></span>
              <div class="form-inputs">
                <%= render partial: "#{fields2}", locals: { f: f } %>
              </div>
            </div>
          </div>    
        </div>              
      </div>
    </div>

      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
    <ul class="right">
      <li><%= link_to 'Login', login_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_owner.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'My Account', owner_path(current_user.owner) %></li>
      <li><%= link_to 'My Pets', pets_path %></li>
      <li><%= link_to 'My Visits', visits_path %></li>

    </ul>
    <ul class="right">
      <li><%= link_to 'Logout', logout_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <% if can? :index, eval(model_name.capitalize) %>
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can? :edit, object %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can?(:destroy, object) && controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>
</div>

app/views/partials/_search_form.html.erb
<%= form_with url: search_path, method: :get, class: "form-inline", id: "search" do %>
    <%= text_field_tag 'query', '', placeholder: "Search ..." %>
    <!-- submitting via js (press enter) so not using... -->
    <%# submit_tag('Find') %>
  
<% end %>

app/views/partials/_structure1.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

app/views/partials/_structure2.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options", locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_title_with_search.html.erb
  <div class="row">
    <div class="col s7">
      <h4><%= title %></h4>
    </div>
    <div class="col s5">

          <%# form_with url: search_path, method: :get, class: "form-inline", id: "search" do %>
              <%# text_field_tag 'query', '', placeholder: "Search ..." %>
              <!-- submitting via js (press enter) so not using... -->
              <%# submit_tag('Find') %>
            
          <%# end %>

    </div>
  </div>
  

app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
    <%= link_to(image_tag('logos/logo_v2_80x80.png'), home_path) %>
  </div>
  <div class="col s8">
    <!-- <h2>Pittsburgh Animal Treatment Services</h2> -->
    <h2>Pgh Animal Treatment Services</h2>
  </div>
  <div class="col s2">
    <%= render partial: 'partials/search_form' %>
  </div>
  <div class="col s1">
    &nbsp;
  </div>
</div>