config/routes.rb
Rails.application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :owners
  resources :animals
  resources :pets
  resources :visits
  resources :dosages
  resources :treatments
  resources :medicines
  resources :procedures

  # Routes for mecidine and procedure costs
  get 'medicine_costs/new', to: 'medicine_costs#new', as: :new_medicine_cost
  get 'procedure_costs/new', to: 'procedure_costs#new', as: :new_procedure_cost
  post 'medicine_costs', to: 'medicine_costs#create', as: :medicine_costs
  post 'procedure_costs', to: 'procedure_costs#create', as: :procedure_costs

  # Other custom routes
  get 'visits/:id/dosages', to: 'visits#dosages', as: :visit_dosages

  # Routes for searching
  # get 'medicines/search', to: 'medicines#search', as: :medicine_search
  # get 'owners/search', to: 'owners#search', as: :owner_search
  # get 'pets/search', to: 'pets#search', as: :pet_search

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/procedure.rb
require 'helpers/activeable'

class Procedure < ApplicationRecord
  include Activeable::InstanceMethods
  extend Activeable::ClassMethods

  # Relationships
  has_many :procedure_costs
  has_many :treatments
  has_many :visits, through: :treatments

  # Scopes (in addition to activeable ones)
  scope :alphabetical, -> { order('name') }

  # Validations
  validates_presence_of :name
  validates_numericality_of :length_of_time, only_integer: true, greater_than: 0
  
  # Other methods
  def current_cost
    curr_cost_of_procedure = self.procedure_costs.current    
    return nil if curr_cost_of_procedure.empty?
    curr_cost_of_procedure.first.cost
  end

  # Callbacks
  before_destroy do 
   check_if_ever_given_as_treatment
   @destroyable = false if errors.present?
   throw(:abort) if errors.present?
   remove_associated_procedure_costs
  end

  after_rollback :convert_to_inactive

  private
  def check_if_ever_given_as_treatment
    unless no_treatments?
      errors.add(:base, "Procedure cannot be deleted because previously used during visits, but its status has been set to inactive.")
    end
  end

  def no_treatments?
    self.treatments.empty?
  end

  def remove_associated_procedure_costs
    self.procedure_costs.each{ |pc| pc.destroy }
  end

  def convert_to_inactive
    if !@destroyable.nil? && @destroyable == false
      self.update_column(:active, false)
    end
    @destroyable = nil
  end

end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController

  before_action :set_procedure, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    # get all visits in reverse chronological order, 10 per page
    @procedures = Procedure.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def show
    # get the cost history for this procedure
    @prices = @procedure.procedure_costs.chronological #.to_a.reverse
  end
  
  def new
    @procedure = Procedure.new
  end
  
  def create
    @procedure = Procedure.new(procedure_params)
    if @procedure.save
      flash[:notice] = "Successfully added #{@procedure.name}."
      redirect_to @procedure
    else
      render action: 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @procedure.update(procedure_params)
      flash[:notice] = "Successfully updated #{@procedure.name}."
      redirect_to @procedure
    else
      render action: 'edit'
    end
  end
  
  def destroy
    if @procedure.destroy
      flash[:notice] = "Successfully removed #{@procedure.name}."
      redirect_to procedures_url
    else
      @prices = @procedure.procedure_costs.chronological
      render action: 'show'
    end
    
  end

  private
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    def procedure_params
      params.require(:procedure).permit(:name, :description, :length_of_time, :active)
    end
end

app/views/procedures/_cost_history.html.erb
<% unless @prices.empty? %>
  <div class="card">
    <div class="card-content">
      <span class="card-title">Cost History</span>
      <table class="striped highlight">
      <thead>
        <th>Date</th>
        <th class="align_right">Cost</th>
      </thead>
        <% for price in @prices %>
          <tr>
            <td><%= price.start_date.strftime("%b %d, %Y") %></td>
          <td class="align_right"><%= number_to_currency(price.cost/100) %></td>
          </tr>
        <% end %>
    </table>
    </div>
    <% if can? :new, ProcedureCost %>
      <div class="card-action">
        <%= link_to "Add a new cost", new_procedure_cost_path(procedure_id: @procedure.id) %>
      </div>
    <% end %>
  </div>
<% else %>
  <% if can? :new, ProcedureCost %>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add a new cost", new_procedure_cost_path(procedure_id: @procedure.id) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/procedures/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :description, label_html: { class: 'active' } %>
<%= f.input :length_of_time, label_html: { class: 'active' } %>
<%= f.input :active %>

app/views/procedures/_form.html.erb
<%= simple_form_for(@procedure) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :name, label_html: { class: 'active' } %>
      <%= f.input :description, label_html: { class: 'active' } %>
      <%= f.input :length_of_time, label_html: { class: 'active' } %>
      <%= f.input :active %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/procedures/_procedure_data.html.erb
<div class="card">
  <div class="card-content">
    <h5>Information for <%= @procedure.name %></h5><br />

    <b>Description:&nbsp;&nbsp;</b>
      <%= @procedure.description %><br /><br />

    <b>Time to perform:&nbsp;&nbsp;</b>
      <%= @procedure.length_of_time %> minutes<br /><br />

    <b>Currently offered?&nbsp;&nbsp;</b>
      <%= @procedure.active ? "Yes" : "No" %><br><br><br>
  </div>
</div>

app/views/procedures/_procedures_list.html.erb
<h4>Procedures at PATS</h4>

<table class="striped highlight">
  <thead>
    <th>Name</th>
    <th class="align_center">Minutes</th>
    <th class="align_center">Current Cost</th>
    <% if current_user.vet? %>
      <th class="align_center">Options</th>
    <% end %>
  </thead>
  <% for procedure in @procedures %>
    <tr>
      <td><%= link_to procedure.name, procedure_path(procedure) %></td>
      <td class="align_center"><%= procedure.length_of_time %></td>
      <td class="align_center"><%= procedure.current_cost.nil? ? 'N/A' : number_to_currency(procedure.current_cost/100) %></td>
      <% if current_user.vet? %>
        <td class="align_center">
        <%= link_to edit_procedure_path(procedure) do %>
              <i class="material-icons">edit</i>
          <% end %>
          &nbsp;&nbsp;&nbsp;&nbsp; 
          <%= link_to(procedure_path(procedure), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
              <i class="material-icons">delete</i>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<br />
<%= will_paginate @procedures, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<p>&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'procedure'} %>

app/views/procedures/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @procedure, 
                                                        type_of_form: "Edit Procedure",
                                                        fields: "fields"} %>

app/views/procedures/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "procedure", 
                                                         primary: "procedures_list", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/procedures/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @procedure, 
                                                        type_of_form: "New Procedure",
                                                        fields: "fields"} %>

app/views/procedures/show.html.erb
<%= render partial: "partials/structure2", locals: {model_name: "procedure", 
                                                         object: @procedure,
                                                         primary: "procedure_data", 
                                                         secondary: nil,
                                                         sidebar: "cost_history"} %>